background {
    monitor =
    path = /home/KJ/.config/hypr/lockbg.png
    blur_passes = 3
    blur_size = 7
    brightness = 0.5
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    outer_color = rgb(EF3946)
    inner_color = rgb(0D0D1A)
    font_color = rgb(FEE5E4)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    check_color = rgb(00FF9F)
    fail_color = rgb(EF3946)
    fail_text = <i>Wrong password!</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(FEE5E4ff)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %B %d"
    color = rgba(EF3946ff)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, 120
    halign = center
    valign = center
}
