windowrule = match:class ^(floating-cava)$, float on, size 800 400, center on
windowrule = match:class ^(firefox)$, workspace 1
windowrule = match:class ^(org.telegram.desktop)$, workspace 11
windowrule = workspace 11, match:class ^(firefox)$
